apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: 345999536858.dkr.ecr.us-east-1.amazonaws.com/go-app-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-app-service:27017"
            - name: APP_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
spec:
  type: ClusterIP
  selector:
    app: go-app  # Adjusted to match the labels in the deployment
  ports:
    - name: go-app
      port: 8080
      targetPort: 8080
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  ingressClassName: 
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-app-svc 
                port:
                  number: 8080


