name: kubernetes deployment 
on: 
  pull_request:
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - name: install kubectl 
        uses: azure/setup-kubectl@v3
        with:
          version: latest
      - name: verify kubectl 
        run: |
          kubectl version --client 
      - name: update kubecofig 
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubecofig
      - name: apply kubenetes mainfest files
        run: |
          export KUBECONFIG=kubecofig
          kubectl apply -f k8s/ 
          sleep 60s
          kubectl get svc 

